### ISSUE TITLE
compiling?

### ISSUE THREAD

**Issue by Sophrinix** [AppWerft/Ti.ParseLiveQuery#1]
when I use ```ant```, and of course do all the normal titanium module compile things (set build.properties, etc), I still run into this:
```
process.annotations:
    [mkdir] Created dir: /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/build/generated/json
    [javac] Compiling 6 source files to /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] Note: [KrollBindingGen] Running Kroll binding generator.
    [javac] Note: [KrollBindingGen] No binding data found, creating new data file: org.appcelerator.titanium.bindings/parselivequery.json
    [javac] Note: [KrollBindingGen] Found binding for proxy Object
    [javac] Note: [KrollBindingGen] Found binding for module Parselivequery
    [javac] Note: [KrollBindingGen] Found binding for proxy Query
    [javac] Note: [KrollBindingGen] Generating JSON: file:/Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/build/generated/json/org/appcelerator/titanium/bindings/parselivequery.json
    [javac] /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/src/de/appwerft/parselivequery/ObjectProxy.java:58: error: local variable kcb is accessed from within inner class; needs to be declared final
    [javac] 					kcb.onSuccess.call(getKrollObject(), new KrollDict());
    [javac] 					^
    [javac] /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/src/de/appwerft/parselivequery/ObjectProxy.java:60: error: local variable kcb is accessed from within inner class; needs to be declared final
    [javac] 					kcb.onError.call(getKrollObject(), new KrollDict());
    [javac] 					^
    [javac] /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/src/de/appwerft/parselivequery/ObjectProxy.java:110: error: local variable kcb is accessed from within inner class; needs to be declared final
    [javac] 					if (kcb.onSuccess != null)
    [javac] 					    ^
    [javac] /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/src/de/appwerft/parselivequery/ObjectProxy.java:111: error: local variable kcb is accessed from within inner class; needs to be declared final
    [javac] 						kcb.onSuccess.call(getKrollObject(), res);
    [javac] 						^
    [javac] Note: /Users/andrewmcelroy/repos/shouse-repos/wtf/wat/Ti.ParseLiveQuery/android/src/de/appwerft/parselivequery/QueryProxy.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 errors
```

what are your steps for compiling. I am trying to compile with 6.1.2.GA

**Comment by shouse** [comment]
Similar issues.  Let's make some better documentation.  I'll offer help.
